In [1]:
import pandas as pd
import glob
import os
from pathlib import Path

In [64]:
# ================================
# 1. LOAD ALL FILES (SAFE)
# ================================

folder = Path(r"C:\Users\ibrahim.zimit\Desktop\2024")

files = [f for f in folder.glob("*.csv") if not f.name.startswith("~$")]

print("Folder exists:", folder.exists())

print("Valid files found:", len(files))

print("\n--- ROOT CONTENT ---")
for item in folder.iterdir():
    print(item.name)

Folder exists: True
Valid files found: 6

--- ROOT CONTENT ---
Aug-2024.csv
Dec-2024.csv
Jul-2024.csv
Nov-2024.csv
Oct-2024.csv
Sep-2024.csv

In [65]:
df_list = []

for file in files:
    try:
        print("Reading:", file)

        temp = pd.read_csv(
            file,
            low_memory=False,
            on_bad_lines="skip",
            encoding="latin1"
        )

        df_list.append(temp)

        print("✅ Loaded:", temp.shape)

    except Exception as e:
        print(f"❌ Failed {file}: {e}")

df = pd.concat(df_list, ignore_index=True)

print("Final shape:", df.shape)

Reading: C:\Users\ibrahim.zimit\Desktop\2024\Aug-2024.csv
✅ Loaded: (468012, 25)
Reading: C:\Users\ibrahim.zimit\Desktop\2024\Dec-2024.csv
✅ Loaded: (451454, 23)
Reading: C:\Users\ibrahim.zimit\Desktop\2024\Jul-2024.csv
✅ Loaded: (426522, 30)
Reading: C:\Users\ibrahim.zimit\Desktop\2024\Nov-2024.csv
✅ Loaded: (450842, 23)
Reading: C:\Users\ibrahim.zimit\Desktop\2024\Oct-2024.csv
✅ Loaded: (460670, 24)
Reading: C:\Users\ibrahim.zimit\Desktop\2024\Sep-2024.csv
✅ Loaded: (455424, 24)
Final shape: (2712924, 62)

In [67]:
df

,ACCOUNT NUMBER,CUSTOMER,ADDRESS,PHONE,FINAL READING,INITIAL READING,MULTIPLIER,CONSUMPTION,TARIFF,RATE,...,TotalDue,OldAcctNo,Mobile,PREVIOUS CLOSING BALANCE,OPENING BALANCE,PREVIOUS PAYMENTS,ADJUSTMENTS TOTAL,CLOSING BAL,BILL NUMBER,CLOSING BALANCE
0,36/13/20/4428-01,Ibrahim Nura,70 DMK gari danmaliki kumbotso 090414091010268...,07035000320 070350,0,0,1,144,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34/55/30/0270-01,Nura Kayawa,56 modoji katsina Gidan Mai unguwa 09051502101...,08035304109 080353,0,0,1,267,B1,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36/21/64/0518-01,Kamilu Muhammad,1032 hausawa fulani kano tarauni murtala muham...,NaN,0,0,1,160,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38/20/05/6892-01,Muhammed Usman,TUDUN TANDA JIGAWA,8025217696,0,0,1,31,D5,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39/41/83/4067-01,Abdullahi Hassan,MAKOLE PRIMARY MAKOLE PRIMARYWUDIL BMAKOLE KANO,8033570592,0,0,1,215,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2712919,39/12/90/0678-01,Ehealth Africa Sys.,"EHEALTH AFRICA SYS. FOUNDATION LTD DAKATA 4, S...",9087395340,3119600.0,3090230.0,1.0,NaN,A12,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J51929862,10693089.51
2712920,32/20/93/0855-01,M. C. Plast,PHASE I SHARADA SHARADA PHASE I KANO,64648724,459980.0,314590.0,1.0,NaN,A13,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J83635620,83119426.92
2712921,31/12/92/0781-01,Khedco,"21,CIVIC CENTRE KANO NO,21 CIVIC CENTRE",8102813189,52379.0,51601.0,1.0,NaN,A8,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J45680153,1604649.27
2712922,38/23/90/0637-01,Garki Lg Street,LOCAL GOVT QTRS GARKI TOWN,7030154226,44561.0,41901.0,1.0,NaN,C14,54.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J34487456,154441.6
2712923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df.head(50)

,ACCOUNT NUMBER,CUSTOMER,ADDRESS,PHONE,FINAL READING,INITIAL READING,MULTIPLIER,CONSUMPTION,TARIFF,RATE,...,TotalDue,OldAcctNo,Mobile,PREVIOUS CLOSING BALANCE,OPENING BALANCE,PREVIOUS PAYMENTS,ADJUSTMENTS TOTAL,CLOSING BAL,BILL NUMBER,CLOSING BALANCE
0,36/13/20/4428-01,Ibrahim Nura,70 DMK gari danmaliki kumbotso 090414091010268...,07035000320 070350,0,0,1,144,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34/55/30/0270-01,Nura Kayawa,56 modoji katsina Gidan Mai unguwa 09051502101...,08035304109 080353,0,0,1,267,B1,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36/21/64/0518-01,Kamilu Muhammad,1032 hausawa fulani kano tarauni murtala muham...,NaN,0,0,1,160,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38/20/05/6892-01,Muhammed Usman,TUDUN TANDA JIGAWA,8025217696,0,0,1,31,D5,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39/41/83/4067-01,Abdullahi Hassan,MAKOLE PRIMARY MAKOLE PRIMARYWUDIL BMAKOLE KANO,8033570592,0,0,1,215,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,38/21/61/0989-01,Ali Abula,YALWAI BUJIRI KKASAMMA,NaN,0,0,1,31,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,34/60/17/1889-01,Tukur Jariri,29 Kofar soro Katsina kofar soro 0905100310101...,NaN,0,0,1,215,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,34/55/35/3904-01,Isah Ibrahim,MODOJI AREA HASSAN USMAN MODOJI 2,8037996443,0,0,1,267,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,39/34/76/1808-01,Mujittaf Adamu,JOGANA KANO KANO,70687934400,0,0,1,90,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,39/06/13/0375-01,Saibiu Iliyasu,RAUDAKEYI M GIGINYA S9100RK22B0070 KANO KN,NaN,0,0,1,166,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,30/63/22/8805-01,MANNIRU YUSIF,1417 KURNA ASABE C LAYIN BABA MADO KANO KANO,NaN,0,0,1,100,B1,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,37/46/06/2218-01,Musa Maina,NO 1197 RIMIN KEBE KN DABINAI SS,8038700299,0,0,1,136,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,34/85/09/0698-01,Muhammd Bishir,SUNGUWA AREA KMARUSAT WALLE3 RLF10049 KATSINA,8034750931,0,0,1,240,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,39/12/24/3712-01,Tijjani Abubakar Adamu,no38 line shuaibu yols kano hotoro massalasi j...,7038505061,0,0,1,118,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,38/22/48/0065-01,Alhassan Yau,MAKADDARI VILL HDJ,NaN,0,0,1,22,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,37/20/09/5726-01,Idiatu Abdulfatai,TWADA QTRS KANO TWADA QRTS,NaN,0,0,1,186,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,38/21/44/2454-01,Usman Alhaji,KIRIKASAMMA TOWN JIGAWA,NaN,0,0,1,118,D1,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,34/55/30/3842-01,Auwal Abubakar L.,MODOJI AREA,7033299051,0,0,1,267,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,31/31/86/2722-01,Isah Garba,KAWON LAMBU LAYIN GARKUWA KANO CENTRAL KANO,NaN,0,0,1,-,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,34/85/18/3741-01,Yushau Aliyu,BEHIND AUDU MANAGER FILLING STATION KMARUSA KM...,NaN,0,0,1,240,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,36/53/29/0060-01,Haruna Isyaku,SABON GARI,NaN,0,0,1,198,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,36/41/07/2543-01,Sadiq Aminu,NEAR GIDAN HAKIMI KURA LGA KANO KANO,070 36447549,0,0,1,-,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,36/34/10/8449-01,Sayadi Ibrahim,DANGORO BADAUDA,081 00607215,0,0,1,137,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,38/21/56/0242-01,M.shaabu Yusif,HADEJIA,NaN,0,0,1,125,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,34/83/24/0510-01,Usman Sani,33 ATC Katsina City unwala Area 09051505201025...,8036518478,0,0,1,212,C1,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,36/34/11/7797-01,Sabiu Korau,Dangoro UKudu Dangoro relief Tamburawa,8134520257,0,0,1,137,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,39/10/03/1812-01,Abdullahi Abbas,Ado Gano street S1003720219 Nrc Tarauni Old,7030883981,0,0,1,131,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,34/60/73/0075-01,Deni Abubakar,KDURBI AREA POLY0000,NaN,0,0,1,215,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,36/54/04/8917-01,Taheer Haruna,Hayin Yawa street Malamawa Falgore Malamawa,8038021641,0,0,1,210,E2,31.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,35/11/51/4036-01,J Flat,TSAURE TSAURE,NaN,0,0,1,202,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,39/32/08/0480-01,Maimuna Abdulrazak,146MAKAU-GV makau street kano MOSQUE 090313031...,08065854520 080658,0,0,1,136,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,39/31/30/7222-01,KABIRU HALADU,WALAWAI CLOSE TO RAMIN BIRJI KANO KN,7037370303,0,0,1,136,C1,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,36/21/05/2778-01,Nuhu Ibrahim,"NO. 1667, TUKUNTAWA TUKUNTAWA KANO",8022662871,0,0,1,213,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,38/21/40/0410-01,Mall Gambo,KADUMEN TUDU HDJ,NaN,0,0,1,185,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,37/46/06/1391-01,Mohammad Garba,719 dabinia Uku rinmin kebe kano uku 090214041...,08028820111 080369,0,0,1,136,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,34/85/12/0208-01,Abdulmalik Malam,NEW PALACE Katsina 09051505301015301101302104 ...,08165653414 080347,0,0,1,240,D1,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,36/41/43/2852-01,Ishaq Aminu,Danhassan road Kura Karfi Nasarawa 09041417202...,08146031918 081460,0,0,1,137,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,35/51/18/0845-01,Tijjani Ado Madaka,D15 FMBN HOUSING STATE MOPOL BASE DUTSE,8036889949,0,0,1,202,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,37/40/64/0852-01,Sani Musa,LAYIN HAMZA MAI KARE,NaN,0,0,1,1,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,34/60/42/0047-01,Hajiya Abbu,22 Yaranchi Area katsina City Opposite mosque ...,8125565199,0,0,1,285,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,34/60/26/3364-01,Hannafi Umar,113 yara katsina f-samji Yaryara 0905150410101...,NaN,0,0,1,285,C1,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,34/87/27/8396-01,Aminu Rabiu,Sabon Titin Kwado Katsina Area Bin Kattab Mosq...,09036355509 090363,0,0,1,285,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,37/50/12/7277-01,Isah Mohd,LAYIN BABA A ZARIYA NO 539 KANKARE KANO,7061143874,0,0,1,186,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,35/12/52/0145-01,Inusa Haruna,JUWAN TUDU VILLAGE BKUDU,NaN,0,0,1,142,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,36/23/07/6865-01,Farouk Abbas,layin Riruwai Mkw Gabas Maikalwa Relief 3 Yanlemo,8036164239,0,0,1,100,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,30/17/07/2288-01,Haruna Garba Bagwai,R SHEHU STRET R ZAKI KN,8039383031,0,0,1,197,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,30/60/56/2604-01,Kabiru,madigawa kano kano 0902120210202270110160410...,8032881899,0,0,1,120,D2,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,36/51/05/5812-01,Yusuf Danjuma,Kamfa road Tudunwada Unguwar Kamfa NYSC Model ...,08034577182 080345,0,0,1,191,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,39/41/06/5802-01,Shehu Shagari,Kofar Kara Sabon Gari Wudil Market 09051304101...,8064245870,0,0,1,189,C1,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,34/82/08/0636-01,Mallam Abdullahi D,GWARJO VILLAGE JIKAMSHI-MSWDABA10008,8153791854,0,0,1,164,B2,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# ================================
# 2. CLEAN COLUMN NAMES
# ================================
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [44]:
df.columns

Index(['account_number', 'customer', 'address', 'phone', 'final_reading',
       'initial_reading', 'multiplier', 'consumption', 'tariff', 'rate',
       'classification', 'previous_payments', 'previous_closing_balance',
       'opening_balance', 'adjustments_total', 'bill_amount', 'net_arrears',
       'cb', 'period', 'bill_style', 'account_type', 'feeder', 'region',
       'state', 'sbt', 'consumption', 'closing_balance', 'accountno', 'region',
       'accttye', 'billyear', 'billmonth', 'billmonthname', 'customername',
       'prevbalance', 'meterno', 'payment', 'serviceaddress1',
       'serviceaddress2', 'serviceaddress3', 'adjustment', 'netarrears',
       'tariffcode', 'band', 'presentkwh', 'previouskwh', 'multiplier',
       'energy_billed', 'rate', 'fc', 'mmf', 'amount_billed', 'totaldue',
       'oldacctno', 'mobile', 'previous_closing_balance', 'opening_balance',
       'previous_payments', 'adjustments_total', 'closing_bal', 'bill_number',
       'closing_balance'],
      dtype='object')

In [45]:
print(df.isnull().sum())

account_number        426525
customer              426664
address               442745
phone                1129307
final_reading         426525
                      ...
previous_payments    2252255
adjustments_total    2252255
closing_bal          2252255
bill_number          1796832
closing_balance      2257501
Length: 62, dtype: int64

In [46]:
categorical_cols = [
    'customername', 'serviceaddress1', 'type', 'phone',
    'tariff', 'bill_style', 'feeder', 'state',
    'region', 'accountno','meterno' 
]

numeric_cols = [
    'final_reading', 'initial_reading', 'multiplier',
    'consumption', 'rate',
    'previous_closing_balance', 'previous_payments',
    'opening_balance', 'adjustments_total',
    'bill_amount', 'closing_balance'
]

In [48]:
print(df.isnull().sum())

account_number        426525
customer              426664
address               442745
phone                1129307
final_reading         426525
                      ...
previous_payments    2252255
adjustments_total    2252255
closing_bal          2252255
bill_number          1796832
closing_balance      2257501
Length: 62, dtype: int64

In [47]:
df.duplicated().any()

np.True_

In [49]:
# Remove duplicates safely
df = df.loc[:, ~df.columns.duplicated()]

In [50]:
df.duplicated().any()

np.True_

In [51]:
numeric_cols = [col for col in numeric_cols if col in df.columns]

for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '', regex=False)
    )

    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

In [52]:
df.columns

Index(['account_number', 'customer', 'address', 'phone', 'final_reading',
       'initial_reading', 'multiplier', 'consumption', 'tariff', 'rate',
       'classification', 'previous_payments', 'previous_closing_balance',
       'opening_balance', 'adjustments_total', 'bill_amount', 'net_arrears',
       'cb', 'period', 'bill_style', 'account_type', 'feeder', 'region',
       'state', 'sbt', 'closing_balance', 'accountno', 'accttye', 'billyear',
       'billmonth', 'billmonthname', 'customername', 'prevbalance', 'meterno',
       'payment', 'serviceaddress1', 'serviceaddress2', 'serviceaddress3',
       'adjustment', 'netarrears', 'tariffcode', 'band', 'presentkwh',
       'previouskwh', 'energy_billed', 'fc', 'mmf', 'amount_billed',
       'totaldue', 'oldacctno', 'mobile', 'closing_bal', 'bill_number'],
      dtype='object')

In [53]:
# Remove columns that don't exist
categorical_cols = [col for col in categorical_cols if col in df.columns]

In [54]:
categorical_cols

['customername',
 'serviceaddress1',
 'phone',
 'tariff',
 'bill_style',
 'feeder',
 'state',
 'region',
 'accountno',
 'meterno']

In [55]:
df

,account_number,customer,address,phone,final_reading,initial_reading,multiplier,consumption,tariff,rate,...,previouskwh,energy_billed,fc,mmf,amount_billed,totaldue,oldacctno,mobile,closing_bal,bill_number
0,36/13/20/4428-01,Ibrahim Nura,70 DMK gari danmaliki kumbotso 090414091010268...,07035000320 070350,0.0,0.0,1.0,144.0,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34/55/30/0270-01,Nura Kayawa,56 modoji katsina Gidan Mai unguwa 09051502101...,08035304109 080353,0.0,0.0,1.0,267.0,B1,65.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36/21/64/0518-01,Kamilu Muhammad,1032 hausawa fulani kano tarauni murtala muham...,NaN,0.0,0.0,1.0,160.0,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38/20/05/6892-01,Muhammed Usman,TUDUN TANDA JIGAWA,8025217696,0.0,0.0,1.0,31.0,D5,32.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39/41/83/4067-01,Abdullahi Hassan,MAKOLE PRIMARY MAKOLE PRIMARYWUDIL BMAKOLE KANO,8033570592,0.0,0.0,1.0,215.0,C2,47.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2712919,39/12/90/0678-01,Ehealth Africa Sys.,"EHEALTH AFRICA SYS. FOUNDATION LTD DAKATA 4, S...",9087395340,3119600.0,3090230.0,1.0,0.0,A12,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J51929862
2712920,32/20/93/0855-01,M. C. Plast,PHASE I SHARADA SHARADA PHASE I KANO,64648724,459980.0,314590.0,1.0,0.0,A13,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J83635620
2712921,31/12/92/0781-01,Khedco,"21,CIVIC CENTRE KANO NO,21 CIVIC CENTRE",8102813189,52379.0,51601.0,1.0,0.0,A8,209.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J45680153
2712922,38/23/90/0637-01,Garki Lg Street,LOCAL GOVT QTRS GARKI TOWN,7030154226,44561.0,41901.0,1.0,0.0,C14,54.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J34487456
2712923,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.columns[df.columns.duplicated()]

Index([], dtype='object')

In [18]:
df.loc[:, categorical_cols] = df[categorical_cols].fillna('Unknown')

In [19]:
df.loc[:, numeric_cols] = (
    df[numeric_cols]
    .replace(',', '', regex=True)    
    .apply(pd.to_numeric, errors='coerce')
    .fillna(0)
)

In [20]:
# ================================
# 5. FILTER SELECTED ACCOUNTS
# ================================
accounts = pd.read_excel(r"C:\Users\ibrahim.zimit\Desktop\selected_accounts.xlsx")  # must have column: account_number

df = df[df['accountno'].isin(accounts['accountno'])]

In [21]:
df.columns

Index(['account_number', 'customer', 'address', 'phone', 'final_reading',
       'initial_reading', 'multiplier', 'consumption', 'tariff', 'rate',
       'classification', 'previous_payments', 'previous_closing_balance',
       'opening_balance', 'adjustments_total', 'bill_amount', 'net_arrears',
       'cb', 'period', 'bill_style', 'account_type', 'feeder', 'region',
       'state', 'sbt', 'closing_balance', 'accountno', 'accttye', 'billyear',
       'billmonth', 'billmonthname', 'customername', 'prevbalance', 'meterno',
       'payment', 'serviceaddress1', 'serviceaddress2', 'serviceaddress3',
       'adjustment', 'netarrears', 'tariffcode', 'band', 'presentkwh',
       'previouskwh', 'energy_billed', 'fc', 'mmf', 'amount_billed',
       'totaldue', 'oldacctno', 'mobile', 'closing_bal', 'bill_number'],
      dtype='object')

In [18]:
df.accountno

8          30/11/91/0109-01
9          30/11/91/0412-01
31         30/11/91/0083-01
32         30/11/91/0234-01
69         30/11/91/0029-01
                 ...
3992452    34/62/01/0674-01
3992453    34/62/01/0745-01
3992780    34/80/03/1715-01
3992781    34/80/03/2150-01
3992782    34/80/03/2203-01
Name: accountno, Length: 2193, dtype: object

In [17]:
df.billmonthname

8          APRIL
9          APRIL
31         APRIL
32         APRIL
69         APRIL
           ...
3992452      MAY
3992453      MAY
3992780      MAY
3992781      MAY
3992782      MAY
Name: billmonthname, Length: 2193, dtype: object

In [21]:
df

,accountno,region,state,accttye,billyear,billmonth,billmonthname,customername,prevbalance,meterno,...,region,consumption,closing_balance,previous_closing_balance,opening_balance,previous_payments,adjustments_total,closing_bal,bill_number,closing_balance
8,30/11/91/0109-01,KATSINA CENTRAL REGION,KATSINA,Commercial Account,2024.0,4.0,APRIL,THE DISTRICT MANAGER,4477306.24,501803,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,30/11/91/0412-01,KATSINA CENTRAL REGION,KATSINA,Commercial Account,2024.0,4.0,APRIL,AGRICULTURAL VOL.TRA,2083222.26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,30/11/91/0083-01,KATSINA CENTRAL REGION,KATSINA,Commercial Account,2024.0,4.0,APRIL,THE GEN MANAGER BROADCAST,3998675.04,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,30/11/91/0234-01,KATSINA CENTRAL REGION,KATSINA,Commercial Account,2024.0,4.0,APRIL,BATC D/MA,2735017.86,3NP15669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,30/11/91/0029-01,KATSINA CENTRAL REGION,KATSINA,Commercial Account,2024.0,4.0,APRIL,KANKIA WATER WORKS,12818201.60,3NP06680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3992452,34/62/01/0674-01,KATSINA SOUTH REGION,KATSINA,Commercial Account,2024.0,5.0,MAY,D.S.S FASKAR[,3669945.29,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992453,34/62/01/0745-01,KATSINA SOUTH REGION,KATSINA,Commercial Account,2024.0,5.0,MAY,RENT TRABUNAL,2257794.82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992780,34/80/03/1715-01,KATSINA NORTH REGION,KATSINA,Private Account,2024.0,5.0,MAY,PRINCIPAL HOUSE,570179.97,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992781,34/80/03/2150-01,KATSINA NORTH REGION,KATSINA,Commercial Account,2024.0,5.0,MAY,G. J. S. S RIMI,785418.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992782,34/80/03/2203-01,KATSINA NORTH REGION,KATSINA,Commercial Account,2024.0,5.0,MAY,G. J. S. S JIBIA,866928.76,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.consumption

        consumption consumption
8               NaN         NaN
9               NaN         NaN
31              NaN         NaN
32              NaN         NaN
69              NaN         NaN
...             ...         ...
3992452         NaN         NaN
3992453         NaN         NaN
3992780         NaN         NaN
3992781         NaN         NaN
3992782         NaN         NaN

[2193 rows x 2 columns]

In [22]:
# ================================
# 6. AGGREGATE DATA
# ================================
summary = df.groupby(['state', 'billmonthname']).agg(
    customer_population=('accountno', 'nunique'),
    energy_billed=('consumption', 'sum'),
    amount_billed=('bill_amount', 'sum'),
    payment=('payment', 'sum')
).reset_index()

In [39]:
df

,account_number,customer,address,phone,final_reading,initial_reading,multiplier,consumption,tariff,rate,...,previouskwh,energy_billed,fc,mmf,amount_billed,totaldue,oldacctno,mobile,closing_bal,bill_number
919510,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,4616.0,1384.0,0.0,NaN,73660.98,1.085077e+06,NaN,8024693113,NaN,NaN
919533,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,2610437.0,7000.0,0.0,NaN,1556170.00,1.122958e+08,30/11/91/0421-01,NaN,NaN,NaN
919534,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,603907.0,6715.0,0.0,NaN,357394.12,4.478483e+06,34/11/97/0005-01,8140539819,NaN,NaN
919551,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,610410.0,3200.0,0.0,NaN,170314.40,1.844822e+07,34/11/97/0238-01,8024693113,NaN,NaN
919566,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,110777.0,328.0,0.0,NaN,17457.23,6.933766e+05,34/11/92/0023-01,8024693113,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331815,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,15216.0,250.0,0.0,NaN,17546.69,5.619753e+05,34/80/03/2909-01,NaN,NaN,NaN
1331972,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,33039.0,250.0,0.0,NaN,17546.69,1.140908e+06,34/80/03/3568-01,NaN,NaN,NaN
1332789,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,NaN,251.0,0.0,NaN,12835.58,1.559060e+06,34/32/34/2734-01,NaN,NaN,NaN
1332790,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,NaN,251.0,0.0,NaN,12835.58,2.017226e+06,34/33/22/0004-01,NaN,NaN,NaN
1333062,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,Unknown,0.0,...,15997.0,215.0,0.0,NaN,10994.62,8.838758e+05,34/11/82/9245-01,NaN,NaN,NaN

In [36]:
# ================================
# 7. CREATE EXCEL OUTPUT
# ================================

output_file = r"C:\Users\ibrahim.zimit\Desktop\selected_accounts.xlsx"

with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:

    for state in summary['state'].unique():

        state_df = summary[summary['state'] == state]

        # Create Pivot Table
        pivot = state_df.pivot_table(
            index='month',
            values=[
                'customer_population',
                'energy_billed',
                'amount_billed',
                'payment'
            ],
            aggfunc={
                'customer_population': 'nunique',
                'energy_billed': 'sum',
                'amount_billed': 'sum',
                'payment': 'sum'
            }
        )

        # Sort months
        pivot = pivot.sort_index()

        # Transpose
        pivot = pivot.T

        # Rename rows
        pivot.index = [
            'Amount Billed (₦)',
            'Customer Population',
            'Energy Billed (kWh)',
            'Payment (₦)'
        ]

        # Fill missing values
        pivot = pivot.fillna(0)

        # Export to Excel
        pivot.to_excel(writer, sheet_name=state[:31])

print("✅ Report Generated Successfully!")

✅ Report Generated Successfully!

In [37]:
pivot

                            month
Amount Billed (₦)    0.000000e+00
Customer Population  1.000000e+00
Energy Billed (kWh)  0.000000e+00
Payment (₦)          2.264826e+08